#!/usr/bin/env groovy

try {

        stage('Checkout source') {
            /*
            * For a standalone workflow script, we would use the `git` step
            *
            *
             */
            git url: 'https://github.com/GHDSawner/devops.git',
            branch: 'master'
           
            /*
            * Represents the SCM configuration in a "Workflow from SCM" project build. Use checkout
            * scm to check out sources matching Jenkinsfile with the SCM details from
            * the build that is executing this Jenkinsfile.
            *
            * when not in multibranch: https://issues.jenkins-ci.org/browse/JENKINS-31386
            */
            checkout scm
        }

       
}
catch (exc) {
    echo "Caught: ${exc}"
}

// vim: ft=groovy
