####################################################################################
#server yaml
####################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-server
  name: devops-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - image: gcr.io/devopssample-253918/newserver:$BUILD_NUMBER
        resources: {} 
 
